### ISSUE TITLE
Panic while using podmonitors component in clustering mode

### ISSUE THREAD

**Issue by aerfio** [grafana/alloy#1420]
### What's wrong?

Panic while using podmonitors components, see attached logs

### Steps to reproduce

Start alloy instance with clustering enabled and podmonitors component with clustering=true, helm values:

```yaml
controller:
  type: deployment
  replicas: 1
alloy:
  clustering:
    enabled: true
  configMap:
    content: |
      logging {
        level  = "debug"
        format = "logfmt"
      }
      prometheus.operator.podmonitors "pods" {
        forward_to = [otelcol.receiver.prometheus.default.receiver]
        clustering {
            enabled = true
        }
      }
      otelcol.receiver.prometheus "default" {
        output {
          metrics = [otelcol.exporter.logging.default.input]
        }
      }
      otelcol.exporter.logging "default" {}
```

### System information

K8s Server Version: v1.27.12+rke2r1

### Software version

docker.io/grafana/alloy:v1.2.1, alloy chart 0.5.1

### Configuration

```text
Clustering enabled, 1 replica of alloy pod, 3 podmonitors in the clusters that are targeted by Alloy config
```

### Logs

```text
ts=2024-08-05T12:13:08.106457508Z level=info msg="scrape manager stopped" component_path=/ component_id=prometheus.operator.podmonitors.pods
panic: runtime error: index out of range [0] with length 0

goroutine 238 [running]:
github.com/grafana/alloy/internal/component/prometheus/operator/common.filterTargets(0xc001d517d0, {0x7fd9a03b9fe0, 0xc003394410})
        /src/alloy/internal/component/prometheus/operator/common/crdmanager.go:203 +0x5f1
github.com/grafana/alloy/internal/component/prometheus/operator/common.(*crdManager).Run(0xc00339f200, {0x92bead0, 0xc002ff5450})
        /src/alloy/internal/component/prometheus/operator/common/crdmanager.go:158 +0x925
github.com/grafana/alloy/internal/component/prometheus/operator/common.(*Component).Run.func2()
        /src/alloy/internal/component/prometheus/operator/common/component.go:95 +0x38
created by github.com/grafana/alloy/internal/component/prometheus/operator/common.(*Component).Run in goroutine 190
        /src/alloy/internal/component/prometheus/operator/common/component.go:94 +0x38b
```

**Comment by tshuma1** [comment]
is this fix included in this [version](https://github.com/grafana/alloy/releases/tag/v1.3.0)

**Comment by aerfio** [comment]
Yup, confirmed to work on alloy v1.3.0, v0.6.0 of the chart!
