### ISSUE TITLE
Match prometheus behaviour when using relabeling rules with capital letter action

### ISSUE THREAD

**Issue by tommiz1989** [grafana/alloy#1981]
### What's wrong?

According to the prometheus CRD, it is allowed to use capital letters for actions types, 
e.g.
Both Drop and drop should work

We saw that you are using prometheus fork of version 1.8, and we are using prometheus 2.52 in which it works just fine.

### Steps to reproduce

Introduce any relabel with:

action: Drop 

Note: We tested it with ServiceMonitor relabeling, but i should be the same for global one as well.

### Configuration

I think the above already covers it

### Logs

panic: relabel: unknown relabel action type "Drop"

goroutine 4208 [running]:
github.com/prometheus/prometheus/model/relabel.relabel(0xc001df18f0, 0xc0bc18d4b8)
	/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20240514135907-13889ba362e6/model/relabel/relabel.go:314 +0x96e
github.com/prometheus/prometheus/model/relabel.ProcessBuilder(...)
	/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20240514135907-13889ba362e6/model/relabel/relabel.go:233
github.com/prometheus/prometheus/model/relabel.Process({0xc0182f8300, 0x8, 0x8}, {0xc0033fcab0, 0x1, 0x0?})
	/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20240514135907-13889ba362e6/model/relabel/relabel.go:223 +0x105
github.com/prometheus/prometheus/scrape.mutateSampleLabels({0xc0ba149c00, 0x2, 0x2}, 0xc0bc937a40, 0x0, {0xc0033fcab0, 0x1, 0x1})
	/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20240514135907-13889ba362e6/scrape/scrape.go:620 +0x271
github.com/prometheus/prometheus/scrape.newScrapePool.func1.1({0xc0ba149c00?, 0x2?, 0x2?})
	/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20240514135907-13889ba362e6/scrape/scrape.go:165 +0x2c
github.com/prometheus/prometheus/scrape.(*scrapeLoop).append(0xc0bcb3eb40, {0xbed3fb0, 0xc0bd488fc0}, {0xc00bd10000, 0x2a38d, 0x40000}, {0xc0452b1c40, 0x3a}, {0x1c328c77, 0xedeb14e66, ...})
	/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20240514135907-13889ba362e6/scrape/scrape.go:1605 +0x7ac
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc0bcb3eb40, {0xedeb14e66?, 0x1221c9e0?, 0x0?}, {0xedeb14e66?, 0x1221c9e0?, 0x1221c9e0?}, 0x0)
	/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20240514135907-13889ba362e6/scrape/scrape.go:1352 +0xc1d
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc0bcb3eb40, 0x0)
	/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20240514135907-13889ba362e6/scrape/scrape.go:1247 +0x376
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync in goroutine 4108
	/go/pkg/mod/github.com/grafana/prometheus@v1.8.2-0.20240514135907-13889ba362e6/scrape/scrape.go:524 +0xc3d

**Comment by tommiz1989** [comment]
Still relevant
