### ISSUE TITLE
"grafana_cloud.stack" and "pyroscope.receive_http"

### ISSUE THREAD

**Issue by falahati** [grafana/alloy#2285]
### What's wrong?

Using both `grafana_cloud.stack` and `pyroscope.receive_http` results in a crash on Alloy's startup.

### Steps to reproduce

Alloy is deployed as a docker container with the following command and the specified configuration file:
```bash
  docker run \
  -v ~/config.alloy:/etc/alloy/config.alloy \
  -p 12345:12345 \
  -p 4317:4317 \
  -p 4318:4318 \
  -p 4040:4040 \
  --userns=host --cgroupns=host --privileged --ipc=host --pid=host --uts=host --security-opt="seccomp=unconfined" --security-opt="systempaths=unconfined" --security-opt="label=disable" \
  grafana/alloy:latest \
    run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data --stability.level="experimental" \
    /etc/alloy/config.alloy
```

### System information

Containerized on Darwin ARM64

### Software version

Grafana Alloy 1.5.1 (latest)

### Configuration

```text
// imports the Grafana Cloud module from the Grafana Alloy repository
import.git "grafana_cloud" {
  repository = "https://github.com/grafana/alloy-modules.git"
  revision = "main"
  path = "modules/cloud/grafana/cloud/module.alloy"
  pull_frequency = "15m"
}

// should be read from environment variables, for now hardcoded for testing
grafana_cloud.stack "receivers" {
  stack_name = "XXXX"
  token = "glc_XXXX"
}

// creating a profile endpoint and forwarding to Grafana Cloud directly
pyroscope.receive_http "default" {
  http {
    listen_address = "0.0.0.0"
    listen_port = 4040
  }
  forward_to = [grafana_cloud.stack.receivers.profiles]
  // forward_to = [pyroscope.write.default.receiver]
}

// Defining a `pyroscope.write`, when reading the endpoint or username values from the `grafana_cloud.stack.receivers.info` 
// also results in the same exception when `pyroscope.receive_http` is pointed to the new `pyroscope.write`. 
// But hardcoding the values works.
pyroscope.write "default" {
  endpoint {
    url = grafana_cloud.stack.receivers.info["hpInstanceUrl"]

    basic_auth {
      username = grafana_cloud.stack.receivers.info["hpInstanceId"]
      password = "glc_XXXX"
    }
  }
}
```

### Logs

```text
panic: duplicate metrics collector registration attempted

goroutine 170 [running]:
github.com/prometheus/client_golang/prometheus.(*wrappingRegisterer).MustRegister(0x40034a0a50, {0x4003e4c7c0?, 0x0?, 0x0?})
	/go/pkg/mod/github.com/prometheus/client_golang@v1.20.5/prometheus/wrap.go:104 +0x14c
github.com/prometheus/client_golang/prometheus/promauto.Factory.NewGaugeVec({{0xb4c5728?, 0x40034a0a50?}}, {{0x9dbbefa, 0x16}, {0x0, 0x0}, {0x9d6fbbc, 0xf}, {0x9ecf62d, 0x2b}, ...}, ...)
	/go/pkg/mod/github.com/prometheus/client_golang@v1.20.5/prometheus/promauto/auto.go:308 +0x164
github.com/grafana/dskit/server.NewServerMetrics({{0x9dbbefa, 0x16}, 0x0, {0x9d1922f, 0x3}, {0x40033e9191, 0x7}, 0xfc8, 0x64, {0x9d1922f, ...}, ...})
	/go/pkg/mod/github.com/grafana/dskit@v0.0.0-20240104111617-ea101a3b86eb/server/metrics.go:30 +0x124
github.com/grafana/dskit/server.New({{0x9dbbefa, 0x16}, 0x0, {0x9d1922f, 0x3}, {0x40033e9191, 0x7}, 0xfc8, 0x64, {0x9d1922f, ...}, ...})
	/go/pkg/mod/github.com/grafana/dskit@v0.0.0-20240104111617-ea101a3b86eb/server/server.go:240 +0x40
github.com/grafana/alloy/internal/component/common/net.(*TargetServer).MountAndRun(0x4004b790e0, 0x4004bd7a40)
	/src/alloy/internal/component/common/net/server.go:66 +0xec
github.com/grafana/alloy/internal/component/pyroscope/receive_http.(*Component).Update(0x4002676dc0, {0x8e9ba80?, 0x4004b7a0c0?})
	/src/alloy/internal/component/pyroscope/receive_http/receive_http.go:125 +0x408
github.com/grafana/alloy/internal/runtime/internal/controller.(*BuiltinComponentNode).evaluate(0x40034b4248, 0x4003e4c610)
	/src/alloy/internal/runtime/internal/controller/node_builtin_component.go:293 +0x238
github.com/grafana/alloy/internal/runtime/internal/controller.(*BuiltinComponentNode).Evaluate(0x40034b4248, 0x9a3c540?)
	/src/alloy/internal/runtime/internal/controller/node_builtin_component.go:248 +0x20
github.com/grafana/alloy/internal/runtime/internal/controller.(*Loader).concurrentEvalFn(0x40033bcb60, {0xffff3c572238, 0x40034b4248}, {0xb4ef448, 0x4004b78f00}, {0xb464cc8, 0x4004b78e70}, 0x4004f9d9e0)
	/src/alloy/internal/runtime/internal/controller/loader.go:801 +0x520
github.com/grafana/alloy/internal/runtime/internal/controller.(*Loader).EvaluateDependants.func2()
	/src/alloy/internal/runtime/internal/controller/loader.go:738 +0x3c
github.com/grafana/alloy/internal/runtime/internal/worker.(*workQueue).emitNextTask.func1()
	/src/alloy/internal/runtime/internal/worker/worker_pool.go:181 +0x6c
github.com/grafana/alloy/internal/runtime/internal/worker.(*fixedWorkerPool).start.func1()
	/src/alloy/internal/runtime/internal/worker/worker_pool.go:87 +0x68
created by github.com/grafana/alloy/internal/runtime/internal/worker.(*fixedWorkerPool).start in goroutine 1
	/src/alloy/internal/runtime/internal/worker/worker_pool.go:80 +0x2c
```

**Comment by simonswine** [comment]
@falahati sorry that you hit this and thanks for reporting this: I have just pushed a PR with fix, let us know if you still have issues.

**Comment by erenatas** [comment]
Hi, latest image of alloy still fails on my side with same error
