### ISSUE TITLE
Grafana-agent Errors

### ISSUE THREAD

**Issue by nick-wvu** [grafana/alloy#523]
I'm seeing the following errors
```
C:\Program Files\Grafana Agent>.\agent-windows-amd64.exe -config.file=.\agent-config.yaml
panic: ReqQueryValueEx failed: The system cannot find the file specified. errno 2

goroutine 1 [running]:
github.com/leoluk/perflib_exporter/perflib.QueryNameTable(0x459e310, 0xb, 0xc0000c39e0)
        /go/pkg/mod/github.com/grafana/perflib_exporter@v0.1.1-0.20211013152516-e37e14fb8b0a/perflib/nametable.go:43 +0x330
github.com/leoluk/perflib_exporter/perflib.init.0()
        /go/pkg/mod/github.com/grafana/perflib_exporter@v0.1.1-0.20211013152516-e37e14fb8b0a/perflib/perflib.go:266 +0x45
```

<img width="923" alt="image" src="https://user-images.githubusercontent.com/115032483/194879237-33517e34-fad7-402f-a678-957b17c687d2.png">

<img width="454" alt="image" src="https://user-images.githubusercontent.com/115032483/194878360-13499840-bc25-4de4-bf97-6ce98898e429.png">

**Comment by jharvey10** [comment]
Closing since this issue is quite old and was opened against Agent. If this is still seen as an issue on current versions of Alloy, then please open a new issue and provide diagnostic data for it.
