### ISSUE TITLE
otelcol.auth.basic can't be used in a module

### ISSUE THREAD

**Issue by Noahnc** [grafana/alloy#956]
### What's wrong?

When using the component `otelcol.auth.basic` in a module like so:

module.river
````
declare "example" {
	otelcol.auth.basic "default" {
		username = "your_username"
		password = "your_password"
	}
}
````

and then use it in config.river:

config.river
````
import.file "module" {
	filename  = "ypath_to_your_module_river_file"
}

module.example "default" {
	stack_name = "$STACK_NAME"
	token      = "$GRAFANA_TOKEN"
}
````

Grafana Alloy panics during startup with the following error: `panic: invalid character(s) in type "module_example_default/otelcol_auth_basic_default"`

The issue seems to be caused by the [following commit](https://github.com/open-telemetry/opentelemetry-collector/commit/65cdb184f31da4bdd432667ceca3d7fbf35c6ddf) in the opentelemetry-collector package, that now checks the component name to only contain alphanumeric characters and underscores. Since Grafana Alloy concats the component name with dashes (e.g `module_example_default/otelcol_auth_basic_default` for the above configuration) the validation fails.

Because of this, the panic does not occur if the `otelcol.auth.basic` component is used in the root configuration directly.

It is also worth noting, that the same commit introduced a length limit of 63 characters for this component name, which could be reached fairly easy when using the component in nested modules.

### Steps to reproduce

1. Create a module with a declare block.
2. Add a `otelcol.auth.basic` Block.
3. Add a module reference to your Alloy config.

### Software version

Grafana Alloy 1.1.0

### Configuration

```text
module.river
`
declare "example" {
	otelcol.auth.basic "default" {
		username = "your_username"
		password = "your_password"
	}
}
````

config.river
````
import.file "module" {
	filename  = "ypath_to_your_module_river_file"
}

module.example "default" {
	stack_name = "$STACK_NAME"
	token      = "$GRAFANA_TOKEN"
}
````
```


### Logs

```text
ts=2024-05-30T08:21:19.316092058Z level=error msg="failed to start reporter" err="context canceled"
grafana_alloy-1  | panic: invalid character(s) in type "uplink_grafana_cloud_default/otelcol_auth_basic_default"
grafana_alloy-1  |
grafana_alloy-1  | goroutine 1 [running]:
grafana_alloy-1  | go.opentelemetry.io/collector/component.MustNewType(...)
grafana_alloy-1  |      /go/pkg/mod/go.opentelemetry.io/collector/component@v0.99.0/config.go:156
grafana_alloy-1  | github.com/grafana/alloy/internal/component/otelcol/auth.(*Auth).Update(0xc002e30000, {0x73751c0?, 0xc002e2c360})
grafana_alloy-1  |      /src/alloy/internal/component/otelcol/auth/auth.go:176 +0x79a
grafana_alloy-1  | github.com/grafana/alloy/internal/component/otelcol/auth.New({{0x7fd757263220, 0xc002d7c330}, {0xc002bd3440, 0x37}, {0x8e0e6e0, 0xc002d78320}, {0xc0023314f0, 0x42}, 0xc002d7a280, {0x8e633c0, ...}, ...}, ...)
grafana_alloy-1  |      /src/alloy/internal/component/otelcol/auth/auth.go:106 +0x272
grafana_alloy-1  | github.com/grafana/alloy/internal/component/otelcol/auth/basic.init.0.func1({{0x7fd757263220, 0xc002d7c330}, {0xc002bd3440, 0x37}, {0x8e0e6e0, 0xc002d78320}, {0xc0023314f0, 0x42}, 0xc002d7a280, {0x8e633c0, ...}, ...}, ...)
grafana_alloy-1  |      /src/alloy/internal/component/otelcol/auth/basic/basic.go:24 +0x151
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy/internal/controller.(*BuiltinComponentNode).evaluate(0xc002e28248, 0xc002d7a740)
grafana_alloy-1  |      /src/alloy/internal/alloy/internal/controller/node_builtin_component.go:272 +0x483
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy/internal/controller.(*BuiltinComponentNode).Evaluate(0xc002e28248, 0x6e43b80?)
grafana_alloy-1  |      /src/alloy/internal/alloy/internal/controller/node_builtin_component.go:245 +0x1c
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy/internal/controller.(*Loader).evaluate(0xc002d5a340, {0x8e0e6e0, 0xc002d784b0}, {0x8e88ea0, 0xc002e28248})      
grafana_alloy-1  |      /src/alloy/internal/alloy/internal/controller/loader.go:831 +0x49
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy/internal/controller.(*Loader).Apply.func2({0x7fd757263240, 0xc002e28248})
grafana_alloy-1  |      /src/alloy/internal/alloy/internal/controller/loader.go:201 +0x1085
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy/internal/dag.WalkTopological(0xc002d6da60, {0xc002d71500, 0x3, 0xd3a12f0?}, 0xc0029262a0)
grafana_alloy-1  |      /src/alloy/internal/alloy/internal/dag/walk.go:83 +0x222
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy/internal/controller.(*Loader).Apply(0xc002d5a340, {0xc002d654a0, {0xc002d70c00, 0x5, 0x8}, {0xc002d70bc0, 0x6, 0x8}, {0x0, 0x0, ...}, ...})
grafana_alloy-1  |      /src/alloy/internal/alloy/internal/controller/loader.go:184 +0xb2d
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy.(*Alloy).loadSource(0xc002bf65a0, 0xc002d08a80, 0xc002d654a0, 0xc002d653b0)
grafana_alloy-1  |      /src/alloy/internal/alloy/alloy.go:310 +0x1b8
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy.(*module).LoadBody(0xc002d7a0a0, {0xc002d74000?, 0xc002bef42f?, 0xc002d49d60?}, 0xc002d654a0, 0xc002d653b0)     
grafana_alloy-1  |      /src/alloy/internal/alloy/module.go:171 +0x5e
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy/internal/controller.(*CustomComponentNode).evaluate(0xc0024d1520, 0xc002d49cb0)
grafana_alloy-1  |      /src/alloy/internal/alloy/internal/controller/node_custom_component.go:205 +0x31c
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy/internal/controller.(*CustomComponentNode).Evaluate(0xc0024d1520, 0x6e43b80?)
grafana_alloy-1  |      /src/alloy/internal/alloy/internal/controller/node_custom_component.go:167 +0x1c
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy/internal/controller.(*Loader).evaluate(0xc0024d1380, {0x8e0e6e0, 0xc002bebea0}, {0x8e88e68, 0xc0024d1520})      
grafana_alloy-1  |      /src/alloy/internal/alloy/internal/controller/loader.go:831 +0x49
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy/internal/controller.(*Loader).Apply.func2({0x8e10f60, 0xc0024d1520})
grafana_alloy-1  |      /src/alloy/internal/alloy/internal/controller/loader.go:201 +0x1085
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy/internal/dag.WalkTopological(0xc002d4a380, {0xc002bf4e80, 0x8, 0xd3a12f0?}, 0xc0029272b0)
grafana_alloy-1  |      /src/alloy/internal/alloy/internal/dag/walk.go:83 +0x222
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy/internal/controller.(*Loader).Apply(0xc0024d1380, {0x0, {0xc002804e58, 0x1, 0x1}, {0xc002d4a360, 0x3, 0x4}, {0x0, 0x0, ...}, ...})
grafana_alloy-1  |      /src/alloy/internal/alloy/internal/controller/loader.go:184 +0xb2d
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy.(*Alloy).loadSource(0xc002bf64b0, 0xc002d08620, 0x0, 0x0)
grafana_alloy-1  |      /src/alloy/internal/alloy/alloy.go:310 +0x1b8
grafana_alloy-1  | github.com/grafana/alloy/internal/alloy.(*Alloy).LoadSource(...)
grafana_alloy-1  |      /src/alloy/internal/alloy/alloy.go:294
grafana_alloy-1  | github.com/grafana/alloy/internal/alloycli.(*alloyRun).Run.func4()
grafana_alloy-1  |      /src/alloy/internal/alloycli/cmd_run.go:312 +0x28a
grafana_alloy-1  | github.com/grafana/alloy/internal/alloycli.(*alloyRun).Run(0xc002bf62d0, {0x7ffd54e80c3c, 0x17})
grafana_alloy-1  |      /src/alloy/internal/alloycli/cmd_run.go:345 +0x1067
grafana_alloy-1  | github.com/grafana/alloy/internal/alloycli.runCommand.func1(0xc002bf2600?, {0xc002bfe960?, 0x4?, 0x7b57d7e?})
grafana_alloy-1  |      /src/alloy/internal/alloycli/cmd_run.go:101 +0x2b
grafana_alloy-1  | github.com/spf13/cobra.(*Command).execute(0xc0027e2908, {0xc002bfe8d0, 0x3, 0x3})
grafana_alloy-1  |      /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
grafana_alloy-1  | github.com/spf13/cobra.(*Command).ExecuteC(0xc0025f5b08)
grafana_alloy-1  |      /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
grafana_alloy-1  | github.com/spf13/cobra.(*Command).Execute(...)
grafana_alloy-1  |      /go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
grafana_alloy-1  | github.com/grafana/alloy/internal/alloycli.Run()
grafana_alloy-1  |      /src/alloy/internal/alloycli/alloycli.go:33 +0x2f8
grafana_alloy-1  | main.main()
grafana_alloy-1  |      /src/alloy/main.go:34 +0xf
```

**Comment by Noahnc** [comment]
I just saw that the issue regarding the unallowed dash has been fixed here: https://github.com/grafana/alloy/pull/858.
What remains is the limit of 62 characters, which can be reached fairly easy when using nested modules.

**Comment by Noahnc** [comment]
Hello @tpaschalis

I can confirm that both issues are resolved in the latest build of the alloy-dev image.

Thanks for your support.
